server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/show
    username: root
    password:
mybatis:
  mapper-locations: classpath*:/mappers/*.xml
  type-aliases-package: com.showseckill.model

